import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { supabaseAdmin } from '@/lib/supabase';

export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const resendKey = process.env.RESEND_API_KEY;
  const emailFrom = process.env.EMAIL_FROM;
  const emailTo = process.env.APP_USER_EMAIL;

  if (!resendKey) {
    return NextResponse.json({ error: 'RESEND_API_KEY not configured' }, { status: 400 });
  }

  const db = supabaseAdmin();
  const now = new Date().toISOString().split('T')[0];
  const weekOut = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];

  const { data: followups } = await db
    .from('follow_ups')
    .select('*, company:companies(name), contact:contacts(full_name)')
    .in('status', ['Open', 'In Progress'])
    .lte('due_date', weekOut)
    .order('due_date');

  const rows = (followups ?? []).map((f) => {
    const isOverdue = f.due_date < now;
    const company = (f.company as { name?: string } | null)?.name ?? '';
    const contact = (f.contact as { full_name?: string } | null)?.full_name ?? '';
    return `<tr style="background:${isOverdue ? '#2d0a0a' : 'transparent'}">
      <td style="padding:8px 12px;border-bottom:1px solid #1e2a3a;color:${isOverdue ? '#f87171' : '#e2e8f0'}">${f.title}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #1e2a3a;color:#94a3b8">${f.due_date ?? '—'}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #1e2a3a;color:#94a3b8">${f.priority}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #1e2a3a;color:#94a3b8">${company}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #1e2a3a;color:#94a3b8">${contact}</td>
    </tr>`;
  }).join('');

  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>Weekly Digest</title></head>
<body style="background:#070d1a;color:#e2e8f0;font-family:Inter,sans-serif;padding:32px;max-width:800px;margin:0 auto">
  <h1 style="color:#3b82f6;font-size:20px;margin-bottom:4px">IB Dealflow — Weekly Digest</h1>
  <p style="color:#475569;font-size:13px;margin-bottom:24px">Open tasks due in the next 7 days</p>
  <table style="width:100%;border-collapse:collapse;border:1px solid #1e2a3a;border-radius:8px;overflow:hidden">
    <thead>
      <tr style="background:#0a1225">
        <th style="padding:10px 12px;text-align:left;font-size:11px;color:#475569;text-transform:uppercase;letter-spacing:.05em">Task</th>
        <th style="padding:10px 12px;text-align:left;font-size:11px;color:#475569;text-transform:uppercase;letter-spacing:.05em">Due</th>
        <th style="padding:10px 12px;text-align:left;font-size:11px;color:#475569;text-transform:uppercase;letter-spacing:.05em">Priority</th>
        <th style="padding:10px 12px;text-align:left;font-size:11px;color:#475569;text-transform:uppercase;letter-spacing:.05em">Company</th>
        <th style="padding:10px 12px;text-align:left;font-size:11px;color:#475569;text-transform:uppercase;letter-spacing:.05em">Contact</th>
      </tr>
    </thead>
    <tbody>${rows || '<tr><td colspan="5" style="padding:16px;text-align:center;color:#475569">No tasks due this week</td></tr>'}</tbody>
  </table>
  <p style="color:#1e2a3a;font-size:11px;margin-top:24px">Generated by IB Dealflow Tracker</p>
</body>
</html>`;

  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: { Authorization: `Bearer ${resendKey}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      from: emailFrom,
      to: emailTo,
      subject: `Weekly Digest — ${(followups ?? []).length} tasks due this week`,
      html,
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    return NextResponse.json({ error: err }, { status: 500 });
  }

  return NextResponse.json({ sent: true, count: (followups ?? []).length });
}
